In [1]:
import numpy as np

In [29]:
a=np.zeros((3,4))+1

In [30]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
b=np.zeros((3,1))

In [32]:
b[0,0]=1

In [33]:
b

array([[1.],
       [0.],
       [0.]])

In [34]:
c=(a+1)*b

In [35]:
c

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
c-b

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.max(d)

1.4142135623730951

In [13]:
e=[]
e.append(c)

In [43]:
e

[array([[2., 2., 2.],
        [0., 0., 0.],
        [0., 0., 0.]])]

In [46]:
np.max(e,axis=1)

array([[2., 2., 2.]])

e1

In [42]:
e1

array([[2., 2., 2.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
mat = np.array([[3, 2, 1],
                [4, 5, 6],
                [7, 8, 9]])

# extract the diagonal elements
np.power(mat, 2).diagonal()

array([ 9, 25, 81])

In [50]:
diag.shape

(3,)

In [56]:
a=np.argmin(mat, axis=0)

In [79]:
mat

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.argmin(mat, axis=0)

array([0, 0, 0])

In [60]:
mat-[1,1,1]

array([[-1,  1,  2],
       [-1,  4,  5],
       [-1,  7,  8]])

In [61]:
x = np.array(5)

In [62]:
x

array(5)

In [65]:
m = np.random.rand(3, 3, 3)

# Set the 3D coordinate a of a point
a = (1, 2, 3)

# Perform element-wise subtraction between a and each element of m
result = m - np.array(a)

# The resulting array has the same shape as m
print(result.shape)  # Output: (M, N, P)

(3, 3, 3)


In [66]:
result

array([[[-0.03780841, -1.92082078, -2.63416517],
        [-0.17537574, -1.62202658, -2.03303028],
        [-0.00343291, -1.58692318, -2.83419127]],

       [[-0.74507495, -1.82944992, -2.26258092],
        [-0.54836217, -1.33055919, -2.50580696],
        [-0.03768944, -1.40045431, -2.55930572]],

       [[-0.59795847, -1.35833591, -2.28745255],
        [-0.74901924, -1.58210953, -2.40906814],
        [-0.41773148, -1.31187259, -2.08977095]]])

In [67]:
m

array([[[0.96219159, 0.07917922, 0.36583483],
        [0.82462426, 0.37797342, 0.96696972],
        [0.99656709, 0.41307682, 0.16580873]],

       [[0.25492505, 0.17055008, 0.73741908],
        [0.45163783, 0.66944081, 0.49419304],
        [0.96231056, 0.59954569, 0.44069428]],

       [[0.40204153, 0.64166409, 0.71254745],
        [0.25098076, 0.41789047, 0.59093186],
        [0.58226852, 0.68812741, 0.91022905]]])